# Auto-generated by oxyde generate-stubs
# DO NOT EDIT - This file will be overwritten

from typing import Any, ClassVar, Literal
from datetime import datetime, date, time
from decimal import Decimal
from uuid import UUID

from oxyde import Model
from oxyde.queries import Query, QueryManager

from __future__ import annotations
import oxyde
import pydantic
from fastapi import HTTPException
from freenit.auth import verify
from freenit.config import getConfig

class BaseRole(Model):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    name: str
    def model_post_init(self, __context):
        ...
    async def fetch_users(self) -> list['User']:
        ...
    objects: ClassVar["BaseRoleManager"]


class BaseRoleQuery(Query[BaseRole]):
    """Type-safe Query for BaseRole model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
    ) -> "BaseRoleQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
    ) -> "BaseRoleQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["id", "-id", "name", "-name"]) -> "BaseRoleQuery":  # type: ignore[override]
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "BaseRoleQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "BaseRoleQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "BaseRoleQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["id", "name"]) -> "BaseRoleQuery":  # type: ignore[override]
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "BaseRoleQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "BaseRoleQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "BaseRoleQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "BaseRoleQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "BaseRoleQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["id", "name"]) -> "BaseRoleQuery":  # type: ignore[override]
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "BaseRoleQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["id", "name"]) -> "BaseRoleQuery":  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["id", "name"], flat: bool = False) -> "BaseRoleQuery":  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[BaseRole]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> BaseRole | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> BaseRole | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(  # type: ignore[override]
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class BaseRoleManager(QueryManager[BaseRole]):
    """Type-safe Manager for BaseRole model."""

    # Query building methods (sync, return Query)

    def query(self) -> BaseRoleQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
    ) -> BaseRoleQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
    ) -> BaseRoleQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["id", "name"]) -> BaseRoleQuery:  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["id", "name"], flat: bool = False) -> BaseRoleQuery:  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> BaseRoleQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> BaseRoleQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> BaseRoleQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> BaseRoleQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> BaseRoleQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> BaseRole:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> BaseRole | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[BaseRole, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def update_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[BaseRole, bool]:
        """Get object, create if missing, or update it when defaults are provided."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[BaseRole]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> BaseRole | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> BaseRole | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(  # type: ignore[override]
        self,
        *,
        instance: BaseRole | None = None,
        client: Any | None = None,
        using: str | None = None,
        id: int | None = None,
        name: str | None = None,
    ) -> BaseRole:
        """Create new object."""
        ...

    async def bulk_create(  # type: ignore[override]
        self,
        objects: list[BaseRole],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[BaseRole]:
        """Bulk create objects."""
        ...

    async def bulk_update(  # type: ignore[override]
        self,
        objects: list[BaseRole],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...


class User(Model):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    email: EmailStr
    password: str
    fullname: str | None
    active: bool
    admin: bool
    omemo_bundle: str | None
    def model_post_init(self, __context):
        ...
    def check(self, password: str) -> bool:
        ...
    @classmethod
    async def login(cls, credentials) -> 'User':
        ...
    async def fetch_roles(self) -> list[BaseRole]:
        ...
    objects: ClassVar["UserManager"]


class UserQuery(Query[User]):
    """Type-safe Query for User model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        active: bool | None = None,
        active__in: list[bool] | None = None,
        active__isnull: bool | None = None,
        admin: bool | None = None,
        admin__in: list[bool] | None = None,
        admin__isnull: bool | None = None,
        email: EmailStr | None = None,
        email__in: list[EmailStr] | None = None,
        email__isnull: bool | None = None,
        fullname: str | None = None,
        fullname__contains: str | None = None,
        fullname__icontains: str | None = None,
        fullname__startswith: str | None = None,
        fullname__istartswith: str | None = None,
        fullname__endswith: str | None = None,
        fullname__iendswith: str | None = None,
        fullname__iexact: str | None = None,
        fullname__in: list[str] | None = None,
        fullname__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        omemo_bundle: str | None = None,
        omemo_bundle__contains: str | None = None,
        omemo_bundle__icontains: str | None = None,
        omemo_bundle__startswith: str | None = None,
        omemo_bundle__istartswith: str | None = None,
        omemo_bundle__endswith: str | None = None,
        omemo_bundle__iendswith: str | None = None,
        omemo_bundle__iexact: str | None = None,
        omemo_bundle__in: list[str] | None = None,
        omemo_bundle__isnull: bool | None = None,
        password: str | None = None,
        password__contains: str | None = None,
        password__icontains: str | None = None,
        password__startswith: str | None = None,
        password__istartswith: str | None = None,
        password__endswith: str | None = None,
        password__iendswith: str | None = None,
        password__iexact: str | None = None,
        password__in: list[str] | None = None,
        password__isnull: bool | None = None,
    ) -> "UserQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        active: bool | None = None,
        active__in: list[bool] | None = None,
        active__isnull: bool | None = None,
        admin: bool | None = None,
        admin__in: list[bool] | None = None,
        admin__isnull: bool | None = None,
        email: EmailStr | None = None,
        email__in: list[EmailStr] | None = None,
        email__isnull: bool | None = None,
        fullname: str | None = None,
        fullname__contains: str | None = None,
        fullname__icontains: str | None = None,
        fullname__startswith: str | None = None,
        fullname__istartswith: str | None = None,
        fullname__endswith: str | None = None,
        fullname__iendswith: str | None = None,
        fullname__iexact: str | None = None,
        fullname__in: list[str] | None = None,
        fullname__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        omemo_bundle: str | None = None,
        omemo_bundle__contains: str | None = None,
        omemo_bundle__icontains: str | None = None,
        omemo_bundle__startswith: str | None = None,
        omemo_bundle__istartswith: str | None = None,
        omemo_bundle__endswith: str | None = None,
        omemo_bundle__iendswith: str | None = None,
        omemo_bundle__iexact: str | None = None,
        omemo_bundle__in: list[str] | None = None,
        omemo_bundle__isnull: bool | None = None,
        password: str | None = None,
        password__contains: str | None = None,
        password__icontains: str | None = None,
        password__startswith: str | None = None,
        password__istartswith: str | None = None,
        password__endswith: str | None = None,
        password__iendswith: str | None = None,
        password__iexact: str | None = None,
        password__in: list[str] | None = None,
        password__isnull: bool | None = None,
    ) -> "UserQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["active", "-active", "admin", "-admin", "email", "-email", "fullname", "-fullname", "id", "-id", "omemo_bundle", "-omemo_bundle", "password", "-password"]) -> "UserQuery":  # type: ignore[override]
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "UserQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "UserQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "UserQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["active", "admin", "email", "fullname", "id", "omemo_bundle", "password"]) -> "UserQuery":  # type: ignore[override]
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "UserQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "UserQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "UserQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "UserQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "UserQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["active", "admin", "email", "fullname", "id", "omemo_bundle", "password"]) -> "UserQuery":  # type: ignore[override]
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "UserQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["active", "admin", "email", "fullname", "id", "omemo_bundle", "password"]) -> "UserQuery":  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["active", "admin", "email", "fullname", "id", "omemo_bundle", "password"], flat: bool = False) -> "UserQuery":  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[User]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> User | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> User | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(  # type: ignore[override]
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class UserManager(QueryManager[User]):
    """Type-safe Manager for User model."""

    # Query building methods (sync, return Query)

    def query(self) -> UserQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        active: bool | None = None,
        active__in: list[bool] | None = None,
        active__isnull: bool | None = None,
        admin: bool | None = None,
        admin__in: list[bool] | None = None,
        admin__isnull: bool | None = None,
        email: EmailStr | None = None,
        email__in: list[EmailStr] | None = None,
        email__isnull: bool | None = None,
        fullname: str | None = None,
        fullname__contains: str | None = None,
        fullname__icontains: str | None = None,
        fullname__startswith: str | None = None,
        fullname__istartswith: str | None = None,
        fullname__endswith: str | None = None,
        fullname__iendswith: str | None = None,
        fullname__iexact: str | None = None,
        fullname__in: list[str] | None = None,
        fullname__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        omemo_bundle: str | None = None,
        omemo_bundle__contains: str | None = None,
        omemo_bundle__icontains: str | None = None,
        omemo_bundle__startswith: str | None = None,
        omemo_bundle__istartswith: str | None = None,
        omemo_bundle__endswith: str | None = None,
        omemo_bundle__iendswith: str | None = None,
        omemo_bundle__iexact: str | None = None,
        omemo_bundle__in: list[str] | None = None,
        omemo_bundle__isnull: bool | None = None,
        password: str | None = None,
        password__contains: str | None = None,
        password__icontains: str | None = None,
        password__startswith: str | None = None,
        password__istartswith: str | None = None,
        password__endswith: str | None = None,
        password__iendswith: str | None = None,
        password__iexact: str | None = None,
        password__in: list[str] | None = None,
        password__isnull: bool | None = None,
    ) -> UserQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        active: bool | None = None,
        active__in: list[bool] | None = None,
        active__isnull: bool | None = None,
        admin: bool | None = None,
        admin__in: list[bool] | None = None,
        admin__isnull: bool | None = None,
        email: EmailStr | None = None,
        email__in: list[EmailStr] | None = None,
        email__isnull: bool | None = None,
        fullname: str | None = None,
        fullname__contains: str | None = None,
        fullname__icontains: str | None = None,
        fullname__startswith: str | None = None,
        fullname__istartswith: str | None = None,
        fullname__endswith: str | None = None,
        fullname__iendswith: str | None = None,
        fullname__iexact: str | None = None,
        fullname__in: list[str] | None = None,
        fullname__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        omemo_bundle: str | None = None,
        omemo_bundle__contains: str | None = None,
        omemo_bundle__icontains: str | None = None,
        omemo_bundle__startswith: str | None = None,
        omemo_bundle__istartswith: str | None = None,
        omemo_bundle__endswith: str | None = None,
        omemo_bundle__iendswith: str | None = None,
        omemo_bundle__iexact: str | None = None,
        omemo_bundle__in: list[str] | None = None,
        omemo_bundle__isnull: bool | None = None,
        password: str | None = None,
        password__contains: str | None = None,
        password__icontains: str | None = None,
        password__startswith: str | None = None,
        password__istartswith: str | None = None,
        password__endswith: str | None = None,
        password__iendswith: str | None = None,
        password__iexact: str | None = None,
        password__in: list[str] | None = None,
        password__isnull: bool | None = None,
    ) -> UserQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["active", "admin", "email", "fullname", "id", "omemo_bundle", "password"]) -> UserQuery:  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["active", "admin", "email", "fullname", "id", "omemo_bundle", "password"], flat: bool = False) -> UserQuery:  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> UserQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> UserQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> UserQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> UserQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> UserQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> User:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> User | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[User, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def update_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[User, bool]:
        """Get object, create if missing, or update it when defaults are provided."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[User]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> User | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> User | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(  # type: ignore[override]
        self,
        *,
        instance: User | None = None,
        client: Any | None = None,
        using: str | None = None,
        active: bool | None = None,
        admin: bool | None = None,
        email: EmailStr | None = None,
        fullname: str | None = None,
        id: int | None = None,
        omemo_bundle: str | None = None,
        password: str | None = None,
    ) -> User:
        """Create new object."""
        ...

    async def bulk_create(  # type: ignore[override]
        self,
        objects: list[User],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[User]:
        """Bulk create objects."""
        ...

    async def bulk_update(  # type: ignore[override]
        self,
        objects: list[User],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...


class UserRole(Model):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    user: User | None
    role: BaseRole | None
    user_id: int | None
    role_id: int | None
    objects: ClassVar["UserRoleManager"]


class UserRoleQuery(Query[UserRole]):
    """Type-safe Query for UserRole model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        role: BaseRole | None = None,
        role__in: list[BaseRole] | None = None,
        role__isnull: bool | None = None,
        role_id: int | None = None,
        role_id__gt: int | None = None,
        role_id__gte: int | None = None,
        role_id__lt: int | None = None,
        role_id__lte: int | None = None,
        role_id__between: tuple[int, int] | None = None,
        role_id__range: int | None = None,
        role_id__in: list[int] | None = None,
        role_id__isnull: bool | None = None,
        user: User | None = None,
        user__in: list[User] | None = None,
        user__isnull: bool | None = None,
        user_id: int | None = None,
        user_id__gt: int | None = None,
        user_id__gte: int | None = None,
        user_id__lt: int | None = None,
        user_id__lte: int | None = None,
        user_id__between: tuple[int, int] | None = None,
        user_id__range: int | None = None,
        user_id__in: list[int] | None = None,
        user_id__isnull: bool | None = None,
    ) -> "UserRoleQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        role: BaseRole | None = None,
        role__in: list[BaseRole] | None = None,
        role__isnull: bool | None = None,
        role_id: int | None = None,
        role_id__gt: int | None = None,
        role_id__gte: int | None = None,
        role_id__lt: int | None = None,
        role_id__lte: int | None = None,
        role_id__between: tuple[int, int] | None = None,
        role_id__range: int | None = None,
        role_id__in: list[int] | None = None,
        role_id__isnull: bool | None = None,
        user: User | None = None,
        user__in: list[User] | None = None,
        user__isnull: bool | None = None,
        user_id: int | None = None,
        user_id__gt: int | None = None,
        user_id__gte: int | None = None,
        user_id__lt: int | None = None,
        user_id__lte: int | None = None,
        user_id__between: tuple[int, int] | None = None,
        user_id__range: int | None = None,
        user_id__in: list[int] | None = None,
        user_id__isnull: bool | None = None,
    ) -> "UserRoleQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["id", "-id", "role", "-role", "role_id", "-role_id", "user", "-user", "user_id", "-user_id"]) -> "UserRoleQuery":  # type: ignore[override]
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "UserRoleQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "UserRoleQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "UserRoleQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["id", "role", "role_id", "user", "user_id"]) -> "UserRoleQuery":  # type: ignore[override]
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "UserRoleQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "UserRoleQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "UserRoleQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "UserRoleQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "UserRoleQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["id", "role", "role_id", "user", "user_id"]) -> "UserRoleQuery":  # type: ignore[override]
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "UserRoleQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["id", "role", "role_id", "user", "user_id"]) -> "UserRoleQuery":  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["id", "role", "role_id", "user", "user_id"], flat: bool = False) -> "UserRoleQuery":  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[UserRole]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> UserRole | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> UserRole | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(  # type: ignore[override]
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class UserRoleManager(QueryManager[UserRole]):
    """Type-safe Manager for UserRole model."""

    # Query building methods (sync, return Query)

    def query(self) -> UserRoleQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        role: BaseRole | None = None,
        role__in: list[BaseRole] | None = None,
        role__isnull: bool | None = None,
        role_id: int | None = None,
        role_id__gt: int | None = None,
        role_id__gte: int | None = None,
        role_id__lt: int | None = None,
        role_id__lte: int | None = None,
        role_id__between: tuple[int, int] | None = None,
        role_id__range: int | None = None,
        role_id__in: list[int] | None = None,
        role_id__isnull: bool | None = None,
        user: User | None = None,
        user__in: list[User] | None = None,
        user__isnull: bool | None = None,
        user_id: int | None = None,
        user_id__gt: int | None = None,
        user_id__gte: int | None = None,
        user_id__lt: int | None = None,
        user_id__lte: int | None = None,
        user_id__between: tuple[int, int] | None = None,
        user_id__range: int | None = None,
        user_id__in: list[int] | None = None,
        user_id__isnull: bool | None = None,
    ) -> UserRoleQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        role: BaseRole | None = None,
        role__in: list[BaseRole] | None = None,
        role__isnull: bool | None = None,
        role_id: int | None = None,
        role_id__gt: int | None = None,
        role_id__gte: int | None = None,
        role_id__lt: int | None = None,
        role_id__lte: int | None = None,
        role_id__between: tuple[int, int] | None = None,
        role_id__range: int | None = None,
        role_id__in: list[int] | None = None,
        role_id__isnull: bool | None = None,
        user: User | None = None,
        user__in: list[User] | None = None,
        user__isnull: bool | None = None,
        user_id: int | None = None,
        user_id__gt: int | None = None,
        user_id__gte: int | None = None,
        user_id__lt: int | None = None,
        user_id__lte: int | None = None,
        user_id__between: tuple[int, int] | None = None,
        user_id__range: int | None = None,
        user_id__in: list[int] | None = None,
        user_id__isnull: bool | None = None,
    ) -> UserRoleQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["id", "role", "role_id", "user", "user_id"]) -> UserRoleQuery:  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["id", "role", "role_id", "user", "user_id"], flat: bool = False) -> UserRoleQuery:  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> UserRoleQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> UserRoleQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> UserRoleQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> UserRoleQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> UserRoleQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> UserRole:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> UserRole | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[UserRole, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def update_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[UserRole, bool]:
        """Get object, create if missing, or update it when defaults are provided."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[UserRole]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> UserRole | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> UserRole | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(  # type: ignore[override]
        self,
        *,
        instance: UserRole | None = None,
        client: Any | None = None,
        using: str | None = None,
        id: int | None = None,
        role: BaseRole | None = None,
        role_id: int | None = None,
        user: User | None = None,
        user_id: int | None = None,
    ) -> UserRole:
        """Create new object."""
        ...

    async def bulk_create(  # type: ignore[override]
        self,
        objects: list[UserRole],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[UserRole]:
        """Bulk create objects."""
        ...

    async def bulk_update(  # type: ignore[override]
        self,
        objects: list[UserRole],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...

