# Auto-generated by oxyde generate-stubs
# DO NOT EDIT - This file will be overwritten

from typing import Any, ClassVar, Literal
from datetime import datetime, date, time
from decimal import Decimal
from uuid import UUID

from oxyde import Model
from oxyde.queries import Query, QueryManager

from __future__ import annotations
from datetime import datetime
from uuid import uuid4
import oxyde
import pydantic
from freenit.models.sql.base import OxydeBaseModel

class MailingList(Model):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    name: str
    address: EmailStr
    distribution_address: EmailStr
    archive_address: EmailStr
    description: str | None
    public: bool
    archive_enabled: bool
    moderation_enabled: bool
    principal_id: int | None
    inbox_principal_id: int | None
    archive_principal_id: int | None
    created_at: datetime | None
    updated_at: datetime | None
    objects: ClassVar["MailingListManager"]


class MailingListQuery(Query[MailingList]):
    """Type-safe Query for MailingList model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        address: EmailStr | None = None,
        address__in: list[EmailStr] | None = None,
        address__isnull: bool | None = None,
        archive_address: EmailStr | None = None,
        archive_address__in: list[EmailStr] | None = None,
        archive_address__isnull: bool | None = None,
        archive_enabled: bool | None = None,
        archive_enabled__in: list[bool] | None = None,
        archive_enabled__isnull: bool | None = None,
        archive_principal_id: int | None = None,
        archive_principal_id__gt: int | None = None,
        archive_principal_id__gte: int | None = None,
        archive_principal_id__lt: int | None = None,
        archive_principal_id__lte: int | None = None,
        archive_principal_id__between: tuple[int, int] | None = None,
        archive_principal_id__range: int | None = None,
        archive_principal_id__in: list[int] | None = None,
        archive_principal_id__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        distribution_address: EmailStr | None = None,
        distribution_address__in: list[EmailStr] | None = None,
        distribution_address__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        inbox_principal_id: int | None = None,
        inbox_principal_id__gt: int | None = None,
        inbox_principal_id__gte: int | None = None,
        inbox_principal_id__lt: int | None = None,
        inbox_principal_id__lte: int | None = None,
        inbox_principal_id__between: tuple[int, int] | None = None,
        inbox_principal_id__range: int | None = None,
        inbox_principal_id__in: list[int] | None = None,
        inbox_principal_id__isnull: bool | None = None,
        moderation_enabled: bool | None = None,
        moderation_enabled__in: list[bool] | None = None,
        moderation_enabled__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        principal_id: int | None = None,
        principal_id__gt: int | None = None,
        principal_id__gte: int | None = None,
        principal_id__lt: int | None = None,
        principal_id__lte: int | None = None,
        principal_id__between: tuple[int, int] | None = None,
        principal_id__range: int | None = None,
        principal_id__in: list[int] | None = None,
        principal_id__isnull: bool | None = None,
        public: bool | None = None,
        public__in: list[bool] | None = None,
        public__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "MailingListQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        address: EmailStr | None = None,
        address__in: list[EmailStr] | None = None,
        address__isnull: bool | None = None,
        archive_address: EmailStr | None = None,
        archive_address__in: list[EmailStr] | None = None,
        archive_address__isnull: bool | None = None,
        archive_enabled: bool | None = None,
        archive_enabled__in: list[bool] | None = None,
        archive_enabled__isnull: bool | None = None,
        archive_principal_id: int | None = None,
        archive_principal_id__gt: int | None = None,
        archive_principal_id__gte: int | None = None,
        archive_principal_id__lt: int | None = None,
        archive_principal_id__lte: int | None = None,
        archive_principal_id__between: tuple[int, int] | None = None,
        archive_principal_id__range: int | None = None,
        archive_principal_id__in: list[int] | None = None,
        archive_principal_id__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        distribution_address: EmailStr | None = None,
        distribution_address__in: list[EmailStr] | None = None,
        distribution_address__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        inbox_principal_id: int | None = None,
        inbox_principal_id__gt: int | None = None,
        inbox_principal_id__gte: int | None = None,
        inbox_principal_id__lt: int | None = None,
        inbox_principal_id__lte: int | None = None,
        inbox_principal_id__between: tuple[int, int] | None = None,
        inbox_principal_id__range: int | None = None,
        inbox_principal_id__in: list[int] | None = None,
        inbox_principal_id__isnull: bool | None = None,
        moderation_enabled: bool | None = None,
        moderation_enabled__in: list[bool] | None = None,
        moderation_enabled__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        principal_id: int | None = None,
        principal_id__gt: int | None = None,
        principal_id__gte: int | None = None,
        principal_id__lt: int | None = None,
        principal_id__lte: int | None = None,
        principal_id__between: tuple[int, int] | None = None,
        principal_id__range: int | None = None,
        principal_id__in: list[int] | None = None,
        principal_id__isnull: bool | None = None,
        public: bool | None = None,
        public__in: list[bool] | None = None,
        public__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "MailingListQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["address", "-address", "archive_address", "-archive_address", "archive_enabled", "-archive_enabled", "archive_principal_id", "-archive_principal_id", "created_at", "-created_at", "description", "-description", "distribution_address", "-distribution_address", "id", "-id", "inbox_principal_id", "-inbox_principal_id", "moderation_enabled", "-moderation_enabled", "name", "-name", "principal_id", "-principal_id", "public", "-public", "updated_at", "-updated_at"]) -> "MailingListQuery":  # type: ignore[override]
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "MailingListQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "MailingListQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "MailingListQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["address", "archive_address", "archive_enabled", "archive_principal_id", "created_at", "description", "distribution_address", "id", "inbox_principal_id", "moderation_enabled", "name", "principal_id", "public", "updated_at"]) -> "MailingListQuery":  # type: ignore[override]
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "MailingListQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "MailingListQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "MailingListQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "MailingListQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "MailingListQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["address", "archive_address", "archive_enabled", "archive_principal_id", "created_at", "description", "distribution_address", "id", "inbox_principal_id", "moderation_enabled", "name", "principal_id", "public", "updated_at"]) -> "MailingListQuery":  # type: ignore[override]
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "MailingListQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["address", "archive_address", "archive_enabled", "archive_principal_id", "created_at", "description", "distribution_address", "id", "inbox_principal_id", "moderation_enabled", "name", "principal_id", "public", "updated_at"]) -> "MailingListQuery":  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["address", "archive_address", "archive_enabled", "archive_principal_id", "created_at", "description", "distribution_address", "id", "inbox_principal_id", "moderation_enabled", "name", "principal_id", "public", "updated_at"], flat: bool = False) -> "MailingListQuery":  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[MailingList]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> MailingList | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> MailingList | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(  # type: ignore[override]
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class MailingListManager(QueryManager[MailingList]):
    """Type-safe Manager for MailingList model."""

    # Query building methods (sync, return Query)

    def query(self) -> MailingListQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        address: EmailStr | None = None,
        address__in: list[EmailStr] | None = None,
        address__isnull: bool | None = None,
        archive_address: EmailStr | None = None,
        archive_address__in: list[EmailStr] | None = None,
        archive_address__isnull: bool | None = None,
        archive_enabled: bool | None = None,
        archive_enabled__in: list[bool] | None = None,
        archive_enabled__isnull: bool | None = None,
        archive_principal_id: int | None = None,
        archive_principal_id__gt: int | None = None,
        archive_principal_id__gte: int | None = None,
        archive_principal_id__lt: int | None = None,
        archive_principal_id__lte: int | None = None,
        archive_principal_id__between: tuple[int, int] | None = None,
        archive_principal_id__range: int | None = None,
        archive_principal_id__in: list[int] | None = None,
        archive_principal_id__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        distribution_address: EmailStr | None = None,
        distribution_address__in: list[EmailStr] | None = None,
        distribution_address__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        inbox_principal_id: int | None = None,
        inbox_principal_id__gt: int | None = None,
        inbox_principal_id__gte: int | None = None,
        inbox_principal_id__lt: int | None = None,
        inbox_principal_id__lte: int | None = None,
        inbox_principal_id__between: tuple[int, int] | None = None,
        inbox_principal_id__range: int | None = None,
        inbox_principal_id__in: list[int] | None = None,
        inbox_principal_id__isnull: bool | None = None,
        moderation_enabled: bool | None = None,
        moderation_enabled__in: list[bool] | None = None,
        moderation_enabled__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        principal_id: int | None = None,
        principal_id__gt: int | None = None,
        principal_id__gte: int | None = None,
        principal_id__lt: int | None = None,
        principal_id__lte: int | None = None,
        principal_id__between: tuple[int, int] | None = None,
        principal_id__range: int | None = None,
        principal_id__in: list[int] | None = None,
        principal_id__isnull: bool | None = None,
        public: bool | None = None,
        public__in: list[bool] | None = None,
        public__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> MailingListQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        address: EmailStr | None = None,
        address__in: list[EmailStr] | None = None,
        address__isnull: bool | None = None,
        archive_address: EmailStr | None = None,
        archive_address__in: list[EmailStr] | None = None,
        archive_address__isnull: bool | None = None,
        archive_enabled: bool | None = None,
        archive_enabled__in: list[bool] | None = None,
        archive_enabled__isnull: bool | None = None,
        archive_principal_id: int | None = None,
        archive_principal_id__gt: int | None = None,
        archive_principal_id__gte: int | None = None,
        archive_principal_id__lt: int | None = None,
        archive_principal_id__lte: int | None = None,
        archive_principal_id__between: tuple[int, int] | None = None,
        archive_principal_id__range: int | None = None,
        archive_principal_id__in: list[int] | None = None,
        archive_principal_id__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        distribution_address: EmailStr | None = None,
        distribution_address__in: list[EmailStr] | None = None,
        distribution_address__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        inbox_principal_id: int | None = None,
        inbox_principal_id__gt: int | None = None,
        inbox_principal_id__gte: int | None = None,
        inbox_principal_id__lt: int | None = None,
        inbox_principal_id__lte: int | None = None,
        inbox_principal_id__between: tuple[int, int] | None = None,
        inbox_principal_id__range: int | None = None,
        inbox_principal_id__in: list[int] | None = None,
        inbox_principal_id__isnull: bool | None = None,
        moderation_enabled: bool | None = None,
        moderation_enabled__in: list[bool] | None = None,
        moderation_enabled__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        principal_id: int | None = None,
        principal_id__gt: int | None = None,
        principal_id__gte: int | None = None,
        principal_id__lt: int | None = None,
        principal_id__lte: int | None = None,
        principal_id__between: tuple[int, int] | None = None,
        principal_id__range: int | None = None,
        principal_id__in: list[int] | None = None,
        principal_id__isnull: bool | None = None,
        public: bool | None = None,
        public__in: list[bool] | None = None,
        public__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> MailingListQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["address", "archive_address", "archive_enabled", "archive_principal_id", "created_at", "description", "distribution_address", "id", "inbox_principal_id", "moderation_enabled", "name", "principal_id", "public", "updated_at"]) -> MailingListQuery:  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["address", "archive_address", "archive_enabled", "archive_principal_id", "created_at", "description", "distribution_address", "id", "inbox_principal_id", "moderation_enabled", "name", "principal_id", "public", "updated_at"], flat: bool = False) -> MailingListQuery:  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> MailingListQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> MailingListQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> MailingListQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> MailingListQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> MailingListQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> MailingList:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> MailingList | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[MailingList, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def update_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[MailingList, bool]:
        """Get object, create if missing, or update it when defaults are provided."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[MailingList]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> MailingList | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> MailingList | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(  # type: ignore[override]
        self,
        *,
        instance: MailingList | None = None,
        client: Any | None = None,
        using: str | None = None,
        address: EmailStr | None = None,
        archive_address: EmailStr | None = None,
        archive_enabled: bool | None = None,
        archive_principal_id: int | None = None,
        created_at: datetime | None = None,
        description: str | None = None,
        distribution_address: EmailStr | None = None,
        id: int | None = None,
        inbox_principal_id: int | None = None,
        moderation_enabled: bool | None = None,
        name: str | None = None,
        principal_id: int | None = None,
        public: bool | None = None,
        updated_at: datetime | None = None,
    ) -> MailingList:
        """Create new object."""
        ...

    async def bulk_create(  # type: ignore[override]
        self,
        objects: list[MailingList],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[MailingList]:
        """Bulk create objects."""
        ...

    async def bulk_update(  # type: ignore[override]
        self,
        objects: list[MailingList],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...


class PendingSubscriber(Model):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    mailing_list: MailingList | None
    email: EmailStr
    token: str
    action: str
    created_at: datetime | None
    mailing_list_id: int | None
    objects: ClassVar["PendingSubscriberManager"]


class PendingSubscriberQuery(Query[PendingSubscriber]):
    """Type-safe Query for PendingSubscriber model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        action: str | None = None,
        action__contains: str | None = None,
        action__icontains: str | None = None,
        action__startswith: str | None = None,
        action__istartswith: str | None = None,
        action__endswith: str | None = None,
        action__iendswith: str | None = None,
        action__iexact: str | None = None,
        action__in: list[str] | None = None,
        action__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: EmailStr | None = None,
        email__in: list[EmailStr] | None = None,
        email__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        mailing_list: MailingList | None = None,
        mailing_list__in: list[MailingList] | None = None,
        mailing_list__isnull: bool | None = None,
        mailing_list_id: int | None = None,
        mailing_list_id__gt: int | None = None,
        mailing_list_id__gte: int | None = None,
        mailing_list_id__lt: int | None = None,
        mailing_list_id__lte: int | None = None,
        mailing_list_id__between: tuple[int, int] | None = None,
        mailing_list_id__range: int | None = None,
        mailing_list_id__in: list[int] | None = None,
        mailing_list_id__isnull: bool | None = None,
        token: str | None = None,
        token__contains: str | None = None,
        token__icontains: str | None = None,
        token__startswith: str | None = None,
        token__istartswith: str | None = None,
        token__endswith: str | None = None,
        token__iendswith: str | None = None,
        token__iexact: str | None = None,
        token__in: list[str] | None = None,
        token__isnull: bool | None = None,
    ) -> "PendingSubscriberQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        action: str | None = None,
        action__contains: str | None = None,
        action__icontains: str | None = None,
        action__startswith: str | None = None,
        action__istartswith: str | None = None,
        action__endswith: str | None = None,
        action__iendswith: str | None = None,
        action__iexact: str | None = None,
        action__in: list[str] | None = None,
        action__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: EmailStr | None = None,
        email__in: list[EmailStr] | None = None,
        email__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        mailing_list: MailingList | None = None,
        mailing_list__in: list[MailingList] | None = None,
        mailing_list__isnull: bool | None = None,
        mailing_list_id: int | None = None,
        mailing_list_id__gt: int | None = None,
        mailing_list_id__gte: int | None = None,
        mailing_list_id__lt: int | None = None,
        mailing_list_id__lte: int | None = None,
        mailing_list_id__between: tuple[int, int] | None = None,
        mailing_list_id__range: int | None = None,
        mailing_list_id__in: list[int] | None = None,
        mailing_list_id__isnull: bool | None = None,
        token: str | None = None,
        token__contains: str | None = None,
        token__icontains: str | None = None,
        token__startswith: str | None = None,
        token__istartswith: str | None = None,
        token__endswith: str | None = None,
        token__iendswith: str | None = None,
        token__iexact: str | None = None,
        token__in: list[str] | None = None,
        token__isnull: bool | None = None,
    ) -> "PendingSubscriberQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["action", "-action", "created_at", "-created_at", "email", "-email", "id", "-id", "mailing_list", "-mailing_list", "mailing_list_id", "-mailing_list_id", "token", "-token"]) -> "PendingSubscriberQuery":  # type: ignore[override]
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "PendingSubscriberQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "PendingSubscriberQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "PendingSubscriberQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["action", "created_at", "email", "id", "mailing_list", "mailing_list_id", "token"]) -> "PendingSubscriberQuery":  # type: ignore[override]
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "PendingSubscriberQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "PendingSubscriberQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "PendingSubscriberQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "PendingSubscriberQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "PendingSubscriberQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["action", "created_at", "email", "id", "mailing_list", "mailing_list_id", "token"]) -> "PendingSubscriberQuery":  # type: ignore[override]
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "PendingSubscriberQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["action", "created_at", "email", "id", "mailing_list", "mailing_list_id", "token"]) -> "PendingSubscriberQuery":  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["action", "created_at", "email", "id", "mailing_list", "mailing_list_id", "token"], flat: bool = False) -> "PendingSubscriberQuery":  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[PendingSubscriber]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> PendingSubscriber | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> PendingSubscriber | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(  # type: ignore[override]
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class PendingSubscriberManager(QueryManager[PendingSubscriber]):
    """Type-safe Manager for PendingSubscriber model."""

    # Query building methods (sync, return Query)

    def query(self) -> PendingSubscriberQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        action: str | None = None,
        action__contains: str | None = None,
        action__icontains: str | None = None,
        action__startswith: str | None = None,
        action__istartswith: str | None = None,
        action__endswith: str | None = None,
        action__iendswith: str | None = None,
        action__iexact: str | None = None,
        action__in: list[str] | None = None,
        action__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: EmailStr | None = None,
        email__in: list[EmailStr] | None = None,
        email__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        mailing_list: MailingList | None = None,
        mailing_list__in: list[MailingList] | None = None,
        mailing_list__isnull: bool | None = None,
        mailing_list_id: int | None = None,
        mailing_list_id__gt: int | None = None,
        mailing_list_id__gte: int | None = None,
        mailing_list_id__lt: int | None = None,
        mailing_list_id__lte: int | None = None,
        mailing_list_id__between: tuple[int, int] | None = None,
        mailing_list_id__range: int | None = None,
        mailing_list_id__in: list[int] | None = None,
        mailing_list_id__isnull: bool | None = None,
        token: str | None = None,
        token__contains: str | None = None,
        token__icontains: str | None = None,
        token__startswith: str | None = None,
        token__istartswith: str | None = None,
        token__endswith: str | None = None,
        token__iendswith: str | None = None,
        token__iexact: str | None = None,
        token__in: list[str] | None = None,
        token__isnull: bool | None = None,
    ) -> PendingSubscriberQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        action: str | None = None,
        action__contains: str | None = None,
        action__icontains: str | None = None,
        action__startswith: str | None = None,
        action__istartswith: str | None = None,
        action__endswith: str | None = None,
        action__iendswith: str | None = None,
        action__iexact: str | None = None,
        action__in: list[str] | None = None,
        action__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: EmailStr | None = None,
        email__in: list[EmailStr] | None = None,
        email__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        mailing_list: MailingList | None = None,
        mailing_list__in: list[MailingList] | None = None,
        mailing_list__isnull: bool | None = None,
        mailing_list_id: int | None = None,
        mailing_list_id__gt: int | None = None,
        mailing_list_id__gte: int | None = None,
        mailing_list_id__lt: int | None = None,
        mailing_list_id__lte: int | None = None,
        mailing_list_id__between: tuple[int, int] | None = None,
        mailing_list_id__range: int | None = None,
        mailing_list_id__in: list[int] | None = None,
        mailing_list_id__isnull: bool | None = None,
        token: str | None = None,
        token__contains: str | None = None,
        token__icontains: str | None = None,
        token__startswith: str | None = None,
        token__istartswith: str | None = None,
        token__endswith: str | None = None,
        token__iendswith: str | None = None,
        token__iexact: str | None = None,
        token__in: list[str] | None = None,
        token__isnull: bool | None = None,
    ) -> PendingSubscriberQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["action", "created_at", "email", "id", "mailing_list", "mailing_list_id", "token"]) -> PendingSubscriberQuery:  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["action", "created_at", "email", "id", "mailing_list", "mailing_list_id", "token"], flat: bool = False) -> PendingSubscriberQuery:  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> PendingSubscriberQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> PendingSubscriberQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> PendingSubscriberQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> PendingSubscriberQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> PendingSubscriberQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> PendingSubscriber:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> PendingSubscriber | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[PendingSubscriber, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def update_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[PendingSubscriber, bool]:
        """Get object, create if missing, or update it when defaults are provided."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[PendingSubscriber]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> PendingSubscriber | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> PendingSubscriber | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(  # type: ignore[override]
        self,
        *,
        instance: PendingSubscriber | None = None,
        client: Any | None = None,
        using: str | None = None,
        action: str | None = None,
        created_at: datetime | None = None,
        email: EmailStr | None = None,
        id: int | None = None,
        mailing_list: MailingList | None = None,
        mailing_list_id: int | None = None,
        token: str | None = None,
    ) -> PendingSubscriber:
        """Create new object."""
        ...

    async def bulk_create(  # type: ignore[override]
        self,
        objects: list[PendingSubscriber],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[PendingSubscriber]:
        """Bulk create objects."""
        ...

    async def bulk_update(  # type: ignore[override]
        self,
        objects: list[PendingSubscriber],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...


class ModerationMessage(Model):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    mailing_list: MailingList | None
    message_id: str | None
    subject: str | None
    sender: EmailStr | None
    sent_at: datetime | None
    text_body: str | None
    html_body: str | None
    status: str
    created_at: datetime | None
    decided_at: datetime | None
    mailing_list_id: int | None
    objects: ClassVar["ModerationMessageManager"]


class ModerationMessageQuery(Query[ModerationMessage]):
    """Type-safe Query for ModerationMessage model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        decided_at: datetime | None = None,
        decided_at__gt: datetime | None = None,
        decided_at__gte: datetime | None = None,
        decided_at__lt: datetime | None = None,
        decided_at__lte: datetime | None = None,
        decided_at__between: tuple[datetime, datetime] | None = None,
        decided_at__range: datetime | None = None,
        decided_at__year: int | None = None,
        decided_at__month: int | None = None,
        decided_at__day: int | None = None,
        decided_at__in: list[datetime] | None = None,
        decided_at__isnull: bool | None = None,
        html_body: str | None = None,
        html_body__contains: str | None = None,
        html_body__icontains: str | None = None,
        html_body__startswith: str | None = None,
        html_body__istartswith: str | None = None,
        html_body__endswith: str | None = None,
        html_body__iendswith: str | None = None,
        html_body__iexact: str | None = None,
        html_body__in: list[str] | None = None,
        html_body__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        mailing_list: MailingList | None = None,
        mailing_list__in: list[MailingList] | None = None,
        mailing_list__isnull: bool | None = None,
        mailing_list_id: int | None = None,
        mailing_list_id__gt: int | None = None,
        mailing_list_id__gte: int | None = None,
        mailing_list_id__lt: int | None = None,
        mailing_list_id__lte: int | None = None,
        mailing_list_id__between: tuple[int, int] | None = None,
        mailing_list_id__range: int | None = None,
        mailing_list_id__in: list[int] | None = None,
        mailing_list_id__isnull: bool | None = None,
        message_id: str | None = None,
        message_id__contains: str | None = None,
        message_id__icontains: str | None = None,
        message_id__startswith: str | None = None,
        message_id__istartswith: str | None = None,
        message_id__endswith: str | None = None,
        message_id__iendswith: str | None = None,
        message_id__iexact: str | None = None,
        message_id__in: list[str] | None = None,
        message_id__isnull: bool | None = None,
        sender: EmailStr | None = None,
        sender__in: list[EmailStr] | None = None,
        sender__isnull: bool | None = None,
        sent_at: datetime | None = None,
        sent_at__gt: datetime | None = None,
        sent_at__gte: datetime | None = None,
        sent_at__lt: datetime | None = None,
        sent_at__lte: datetime | None = None,
        sent_at__between: tuple[datetime, datetime] | None = None,
        sent_at__range: datetime | None = None,
        sent_at__year: int | None = None,
        sent_at__month: int | None = None,
        sent_at__day: int | None = None,
        sent_at__in: list[datetime] | None = None,
        sent_at__isnull: bool | None = None,
        status: str | None = None,
        status__contains: str | None = None,
        status__icontains: str | None = None,
        status__startswith: str | None = None,
        status__istartswith: str | None = None,
        status__endswith: str | None = None,
        status__iendswith: str | None = None,
        status__iexact: str | None = None,
        status__in: list[str] | None = None,
        status__isnull: bool | None = None,
        subject: str | None = None,
        subject__contains: str | None = None,
        subject__icontains: str | None = None,
        subject__startswith: str | None = None,
        subject__istartswith: str | None = None,
        subject__endswith: str | None = None,
        subject__iendswith: str | None = None,
        subject__iexact: str | None = None,
        subject__in: list[str] | None = None,
        subject__isnull: bool | None = None,
        text_body: str | None = None,
        text_body__contains: str | None = None,
        text_body__icontains: str | None = None,
        text_body__startswith: str | None = None,
        text_body__istartswith: str | None = None,
        text_body__endswith: str | None = None,
        text_body__iendswith: str | None = None,
        text_body__iexact: str | None = None,
        text_body__in: list[str] | None = None,
        text_body__isnull: bool | None = None,
    ) -> "ModerationMessageQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        decided_at: datetime | None = None,
        decided_at__gt: datetime | None = None,
        decided_at__gte: datetime | None = None,
        decided_at__lt: datetime | None = None,
        decided_at__lte: datetime | None = None,
        decided_at__between: tuple[datetime, datetime] | None = None,
        decided_at__range: datetime | None = None,
        decided_at__year: int | None = None,
        decided_at__month: int | None = None,
        decided_at__day: int | None = None,
        decided_at__in: list[datetime] | None = None,
        decided_at__isnull: bool | None = None,
        html_body: str | None = None,
        html_body__contains: str | None = None,
        html_body__icontains: str | None = None,
        html_body__startswith: str | None = None,
        html_body__istartswith: str | None = None,
        html_body__endswith: str | None = None,
        html_body__iendswith: str | None = None,
        html_body__iexact: str | None = None,
        html_body__in: list[str] | None = None,
        html_body__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        mailing_list: MailingList | None = None,
        mailing_list__in: list[MailingList] | None = None,
        mailing_list__isnull: bool | None = None,
        mailing_list_id: int | None = None,
        mailing_list_id__gt: int | None = None,
        mailing_list_id__gte: int | None = None,
        mailing_list_id__lt: int | None = None,
        mailing_list_id__lte: int | None = None,
        mailing_list_id__between: tuple[int, int] | None = None,
        mailing_list_id__range: int | None = None,
        mailing_list_id__in: list[int] | None = None,
        mailing_list_id__isnull: bool | None = None,
        message_id: str | None = None,
        message_id__contains: str | None = None,
        message_id__icontains: str | None = None,
        message_id__startswith: str | None = None,
        message_id__istartswith: str | None = None,
        message_id__endswith: str | None = None,
        message_id__iendswith: str | None = None,
        message_id__iexact: str | None = None,
        message_id__in: list[str] | None = None,
        message_id__isnull: bool | None = None,
        sender: EmailStr | None = None,
        sender__in: list[EmailStr] | None = None,
        sender__isnull: bool | None = None,
        sent_at: datetime | None = None,
        sent_at__gt: datetime | None = None,
        sent_at__gte: datetime | None = None,
        sent_at__lt: datetime | None = None,
        sent_at__lte: datetime | None = None,
        sent_at__between: tuple[datetime, datetime] | None = None,
        sent_at__range: datetime | None = None,
        sent_at__year: int | None = None,
        sent_at__month: int | None = None,
        sent_at__day: int | None = None,
        sent_at__in: list[datetime] | None = None,
        sent_at__isnull: bool | None = None,
        status: str | None = None,
        status__contains: str | None = None,
        status__icontains: str | None = None,
        status__startswith: str | None = None,
        status__istartswith: str | None = None,
        status__endswith: str | None = None,
        status__iendswith: str | None = None,
        status__iexact: str | None = None,
        status__in: list[str] | None = None,
        status__isnull: bool | None = None,
        subject: str | None = None,
        subject__contains: str | None = None,
        subject__icontains: str | None = None,
        subject__startswith: str | None = None,
        subject__istartswith: str | None = None,
        subject__endswith: str | None = None,
        subject__iendswith: str | None = None,
        subject__iexact: str | None = None,
        subject__in: list[str] | None = None,
        subject__isnull: bool | None = None,
        text_body: str | None = None,
        text_body__contains: str | None = None,
        text_body__icontains: str | None = None,
        text_body__startswith: str | None = None,
        text_body__istartswith: str | None = None,
        text_body__endswith: str | None = None,
        text_body__iendswith: str | None = None,
        text_body__iexact: str | None = None,
        text_body__in: list[str] | None = None,
        text_body__isnull: bool | None = None,
    ) -> "ModerationMessageQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["created_at", "-created_at", "decided_at", "-decided_at", "html_body", "-html_body", "id", "-id", "mailing_list", "-mailing_list", "mailing_list_id", "-mailing_list_id", "message_id", "-message_id", "sender", "-sender", "sent_at", "-sent_at", "status", "-status", "subject", "-subject", "text_body", "-text_body"]) -> "ModerationMessageQuery":  # type: ignore[override]
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "ModerationMessageQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "ModerationMessageQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "ModerationMessageQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["created_at", "decided_at", "html_body", "id", "mailing_list", "mailing_list_id", "message_id", "sender", "sent_at", "status", "subject", "text_body"]) -> "ModerationMessageQuery":  # type: ignore[override]
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "ModerationMessageQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "ModerationMessageQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "ModerationMessageQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "ModerationMessageQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "ModerationMessageQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["created_at", "decided_at", "html_body", "id", "mailing_list", "mailing_list_id", "message_id", "sender", "sent_at", "status", "subject", "text_body"]) -> "ModerationMessageQuery":  # type: ignore[override]
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "ModerationMessageQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["created_at", "decided_at", "html_body", "id", "mailing_list", "mailing_list_id", "message_id", "sender", "sent_at", "status", "subject", "text_body"]) -> "ModerationMessageQuery":  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "decided_at", "html_body", "id", "mailing_list", "mailing_list_id", "message_id", "sender", "sent_at", "status", "subject", "text_body"], flat: bool = False) -> "ModerationMessageQuery":  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[ModerationMessage]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> ModerationMessage | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> ModerationMessage | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(  # type: ignore[override]
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class ModerationMessageManager(QueryManager[ModerationMessage]):
    """Type-safe Manager for ModerationMessage model."""

    # Query building methods (sync, return Query)

    def query(self) -> ModerationMessageQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        decided_at: datetime | None = None,
        decided_at__gt: datetime | None = None,
        decided_at__gte: datetime | None = None,
        decided_at__lt: datetime | None = None,
        decided_at__lte: datetime | None = None,
        decided_at__between: tuple[datetime, datetime] | None = None,
        decided_at__range: datetime | None = None,
        decided_at__year: int | None = None,
        decided_at__month: int | None = None,
        decided_at__day: int | None = None,
        decided_at__in: list[datetime] | None = None,
        decided_at__isnull: bool | None = None,
        html_body: str | None = None,
        html_body__contains: str | None = None,
        html_body__icontains: str | None = None,
        html_body__startswith: str | None = None,
        html_body__istartswith: str | None = None,
        html_body__endswith: str | None = None,
        html_body__iendswith: str | None = None,
        html_body__iexact: str | None = None,
        html_body__in: list[str] | None = None,
        html_body__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        mailing_list: MailingList | None = None,
        mailing_list__in: list[MailingList] | None = None,
        mailing_list__isnull: bool | None = None,
        mailing_list_id: int | None = None,
        mailing_list_id__gt: int | None = None,
        mailing_list_id__gte: int | None = None,
        mailing_list_id__lt: int | None = None,
        mailing_list_id__lte: int | None = None,
        mailing_list_id__between: tuple[int, int] | None = None,
        mailing_list_id__range: int | None = None,
        mailing_list_id__in: list[int] | None = None,
        mailing_list_id__isnull: bool | None = None,
        message_id: str | None = None,
        message_id__contains: str | None = None,
        message_id__icontains: str | None = None,
        message_id__startswith: str | None = None,
        message_id__istartswith: str | None = None,
        message_id__endswith: str | None = None,
        message_id__iendswith: str | None = None,
        message_id__iexact: str | None = None,
        message_id__in: list[str] | None = None,
        message_id__isnull: bool | None = None,
        sender: EmailStr | None = None,
        sender__in: list[EmailStr] | None = None,
        sender__isnull: bool | None = None,
        sent_at: datetime | None = None,
        sent_at__gt: datetime | None = None,
        sent_at__gte: datetime | None = None,
        sent_at__lt: datetime | None = None,
        sent_at__lte: datetime | None = None,
        sent_at__between: tuple[datetime, datetime] | None = None,
        sent_at__range: datetime | None = None,
        sent_at__year: int | None = None,
        sent_at__month: int | None = None,
        sent_at__day: int | None = None,
        sent_at__in: list[datetime] | None = None,
        sent_at__isnull: bool | None = None,
        status: str | None = None,
        status__contains: str | None = None,
        status__icontains: str | None = None,
        status__startswith: str | None = None,
        status__istartswith: str | None = None,
        status__endswith: str | None = None,
        status__iendswith: str | None = None,
        status__iexact: str | None = None,
        status__in: list[str] | None = None,
        status__isnull: bool | None = None,
        subject: str | None = None,
        subject__contains: str | None = None,
        subject__icontains: str | None = None,
        subject__startswith: str | None = None,
        subject__istartswith: str | None = None,
        subject__endswith: str | None = None,
        subject__iendswith: str | None = None,
        subject__iexact: str | None = None,
        subject__in: list[str] | None = None,
        subject__isnull: bool | None = None,
        text_body: str | None = None,
        text_body__contains: str | None = None,
        text_body__icontains: str | None = None,
        text_body__startswith: str | None = None,
        text_body__istartswith: str | None = None,
        text_body__endswith: str | None = None,
        text_body__iendswith: str | None = None,
        text_body__iexact: str | None = None,
        text_body__in: list[str] | None = None,
        text_body__isnull: bool | None = None,
    ) -> ModerationMessageQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        decided_at: datetime | None = None,
        decided_at__gt: datetime | None = None,
        decided_at__gte: datetime | None = None,
        decided_at__lt: datetime | None = None,
        decided_at__lte: datetime | None = None,
        decided_at__between: tuple[datetime, datetime] | None = None,
        decided_at__range: datetime | None = None,
        decided_at__year: int | None = None,
        decided_at__month: int | None = None,
        decided_at__day: int | None = None,
        decided_at__in: list[datetime] | None = None,
        decided_at__isnull: bool | None = None,
        html_body: str | None = None,
        html_body__contains: str | None = None,
        html_body__icontains: str | None = None,
        html_body__startswith: str | None = None,
        html_body__istartswith: str | None = None,
        html_body__endswith: str | None = None,
        html_body__iendswith: str | None = None,
        html_body__iexact: str | None = None,
        html_body__in: list[str] | None = None,
        html_body__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        mailing_list: MailingList | None = None,
        mailing_list__in: list[MailingList] | None = None,
        mailing_list__isnull: bool | None = None,
        mailing_list_id: int | None = None,
        mailing_list_id__gt: int | None = None,
        mailing_list_id__gte: int | None = None,
        mailing_list_id__lt: int | None = None,
        mailing_list_id__lte: int | None = None,
        mailing_list_id__between: tuple[int, int] | None = None,
        mailing_list_id__range: int | None = None,
        mailing_list_id__in: list[int] | None = None,
        mailing_list_id__isnull: bool | None = None,
        message_id: str | None = None,
        message_id__contains: str | None = None,
        message_id__icontains: str | None = None,
        message_id__startswith: str | None = None,
        message_id__istartswith: str | None = None,
        message_id__endswith: str | None = None,
        message_id__iendswith: str | None = None,
        message_id__iexact: str | None = None,
        message_id__in: list[str] | None = None,
        message_id__isnull: bool | None = None,
        sender: EmailStr | None = None,
        sender__in: list[EmailStr] | None = None,
        sender__isnull: bool | None = None,
        sent_at: datetime | None = None,
        sent_at__gt: datetime | None = None,
        sent_at__gte: datetime | None = None,
        sent_at__lt: datetime | None = None,
        sent_at__lte: datetime | None = None,
        sent_at__between: tuple[datetime, datetime] | None = None,
        sent_at__range: datetime | None = None,
        sent_at__year: int | None = None,
        sent_at__month: int | None = None,
        sent_at__day: int | None = None,
        sent_at__in: list[datetime] | None = None,
        sent_at__isnull: bool | None = None,
        status: str | None = None,
        status__contains: str | None = None,
        status__icontains: str | None = None,
        status__startswith: str | None = None,
        status__istartswith: str | None = None,
        status__endswith: str | None = None,
        status__iendswith: str | None = None,
        status__iexact: str | None = None,
        status__in: list[str] | None = None,
        status__isnull: bool | None = None,
        subject: str | None = None,
        subject__contains: str | None = None,
        subject__icontains: str | None = None,
        subject__startswith: str | None = None,
        subject__istartswith: str | None = None,
        subject__endswith: str | None = None,
        subject__iendswith: str | None = None,
        subject__iexact: str | None = None,
        subject__in: list[str] | None = None,
        subject__isnull: bool | None = None,
        text_body: str | None = None,
        text_body__contains: str | None = None,
        text_body__icontains: str | None = None,
        text_body__startswith: str | None = None,
        text_body__istartswith: str | None = None,
        text_body__endswith: str | None = None,
        text_body__iendswith: str | None = None,
        text_body__iexact: str | None = None,
        text_body__in: list[str] | None = None,
        text_body__isnull: bool | None = None,
    ) -> ModerationMessageQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["created_at", "decided_at", "html_body", "id", "mailing_list", "mailing_list_id", "message_id", "sender", "sent_at", "status", "subject", "text_body"]) -> ModerationMessageQuery:  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "decided_at", "html_body", "id", "mailing_list", "mailing_list_id", "message_id", "sender", "sent_at", "status", "subject", "text_body"], flat: bool = False) -> ModerationMessageQuery:  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> ModerationMessageQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> ModerationMessageQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> ModerationMessageQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> ModerationMessageQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> ModerationMessageQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> ModerationMessage:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> ModerationMessage | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[ModerationMessage, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def update_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[ModerationMessage, bool]:
        """Get object, create if missing, or update it when defaults are provided."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[ModerationMessage]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> ModerationMessage | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> ModerationMessage | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(  # type: ignore[override]
        self,
        *,
        instance: ModerationMessage | None = None,
        client: Any | None = None,
        using: str | None = None,
        created_at: datetime | None = None,
        decided_at: datetime | None = None,
        html_body: str | None = None,
        id: int | None = None,
        mailing_list: MailingList | None = None,
        mailing_list_id: int | None = None,
        message_id: str | None = None,
        sender: EmailStr | None = None,
        sent_at: datetime | None = None,
        status: str | None = None,
        subject: str | None = None,
        text_body: str | None = None,
    ) -> ModerationMessage:
        """Create new object."""
        ...

    async def bulk_create(  # type: ignore[override]
        self,
        objects: list[ModerationMessage],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[ModerationMessage]:
        """Bulk create objects."""
        ...

    async def bulk_update(  # type: ignore[override]
        self,
        objects: list[ModerationMessage],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...

