# Auto-generated by oxyde generate-stubs
# DO NOT EDIT - This file will be overwritten

from typing import Any, ClassVar, Literal
from datetime import datetime, date, time
from decimal import Decimal
from uuid import UUID

from oxyde import Model
from oxyde.queries import Query, QueryManager

from __future__ import annotations
from datetime import datetime
import oxyde
import pydantic
from freenit.models.sql.base import OxydeBaseModel, User

class Project(Model):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    name: str
    description: str | None
    created_by: User | None
    created_at: datetime | None
    updated_at: datetime | None
    created_by_id: int | None
    objects: ClassVar["ProjectManager"]


class ProjectQuery(Query[Project]):
    """Type-safe Query for Project model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        created_by: User | None = None,
        created_by__in: list[User] | None = None,
        created_by__isnull: bool | None = None,
        created_by_id: int | None = None,
        created_by_id__gt: int | None = None,
        created_by_id__gte: int | None = None,
        created_by_id__lt: int | None = None,
        created_by_id__lte: int | None = None,
        created_by_id__between: tuple[int, int] | None = None,
        created_by_id__range: int | None = None,
        created_by_id__in: list[int] | None = None,
        created_by_id__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "ProjectQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        created_by: User | None = None,
        created_by__in: list[User] | None = None,
        created_by__isnull: bool | None = None,
        created_by_id: int | None = None,
        created_by_id__gt: int | None = None,
        created_by_id__gte: int | None = None,
        created_by_id__lt: int | None = None,
        created_by_id__lte: int | None = None,
        created_by_id__between: tuple[int, int] | None = None,
        created_by_id__range: int | None = None,
        created_by_id__in: list[int] | None = None,
        created_by_id__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "ProjectQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["created_at", "-created_at", "created_by", "-created_by", "created_by_id", "-created_by_id", "description", "-description", "id", "-id", "name", "-name", "updated_at", "-updated_at"]) -> "ProjectQuery":  # type: ignore[override]
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "ProjectQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "ProjectQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "ProjectQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["created_at", "created_by", "created_by_id", "description", "id", "name", "updated_at"]) -> "ProjectQuery":  # type: ignore[override]
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "ProjectQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "ProjectQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "ProjectQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "ProjectQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "ProjectQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["created_at", "created_by", "created_by_id", "description", "id", "name", "updated_at"]) -> "ProjectQuery":  # type: ignore[override]
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "ProjectQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["created_at", "created_by", "created_by_id", "description", "id", "name", "updated_at"]) -> "ProjectQuery":  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "created_by", "created_by_id", "description", "id", "name", "updated_at"], flat: bool = False) -> "ProjectQuery":  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Project]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Project | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Project | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(  # type: ignore[override]
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class ProjectManager(QueryManager[Project]):
    """Type-safe Manager for Project model."""

    # Query building methods (sync, return Query)

    def query(self) -> ProjectQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        created_by: User | None = None,
        created_by__in: list[User] | None = None,
        created_by__isnull: bool | None = None,
        created_by_id: int | None = None,
        created_by_id__gt: int | None = None,
        created_by_id__gte: int | None = None,
        created_by_id__lt: int | None = None,
        created_by_id__lte: int | None = None,
        created_by_id__between: tuple[int, int] | None = None,
        created_by_id__range: int | None = None,
        created_by_id__in: list[int] | None = None,
        created_by_id__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> ProjectQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        created_by: User | None = None,
        created_by__in: list[User] | None = None,
        created_by__isnull: bool | None = None,
        created_by_id: int | None = None,
        created_by_id__gt: int | None = None,
        created_by_id__gte: int | None = None,
        created_by_id__lt: int | None = None,
        created_by_id__lte: int | None = None,
        created_by_id__between: tuple[int, int] | None = None,
        created_by_id__range: int | None = None,
        created_by_id__in: list[int] | None = None,
        created_by_id__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> ProjectQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["created_at", "created_by", "created_by_id", "description", "id", "name", "updated_at"]) -> ProjectQuery:  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "created_by", "created_by_id", "description", "id", "name", "updated_at"], flat: bool = False) -> ProjectQuery:  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> ProjectQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> ProjectQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> ProjectQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> ProjectQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> ProjectQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Project:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Project | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[Project, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def update_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[Project, bool]:
        """Get object, create if missing, or update it when defaults are provided."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[Project]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Project | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Project | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(  # type: ignore[override]
        self,
        *,
        instance: Project | None = None,
        client: Any | None = None,
        using: str | None = None,
        created_at: datetime | None = None,
        created_by: User | None = None,
        created_by_id: int | None = None,
        description: str | None = None,
        id: int | None = None,
        name: str | None = None,
        updated_at: datetime | None = None,
    ) -> Project:
        """Create new object."""
        ...

    async def bulk_create(  # type: ignore[override]
        self,
        objects: list[Project],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Project]:
        """Bulk create objects."""
        ...

    async def bulk_update(  # type: ignore[override]
        self,
        objects: list[Project],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...


class Board(Model):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    project: Project | None
    name: str
    description: str | None
    created_at: datetime | None
    updated_at: datetime | None
    project_id: int | None
    objects: ClassVar["BoardManager"]


class BoardQuery(Query[Board]):
    """Type-safe Query for Board model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        project: Project | None = None,
        project__in: list[Project] | None = None,
        project__isnull: bool | None = None,
        project_id: int | None = None,
        project_id__gt: int | None = None,
        project_id__gte: int | None = None,
        project_id__lt: int | None = None,
        project_id__lte: int | None = None,
        project_id__between: tuple[int, int] | None = None,
        project_id__range: int | None = None,
        project_id__in: list[int] | None = None,
        project_id__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "BoardQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        project: Project | None = None,
        project__in: list[Project] | None = None,
        project__isnull: bool | None = None,
        project_id: int | None = None,
        project_id__gt: int | None = None,
        project_id__gte: int | None = None,
        project_id__lt: int | None = None,
        project_id__lte: int | None = None,
        project_id__between: tuple[int, int] | None = None,
        project_id__range: int | None = None,
        project_id__in: list[int] | None = None,
        project_id__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "BoardQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["created_at", "-created_at", "description", "-description", "id", "-id", "name", "-name", "project", "-project", "project_id", "-project_id", "updated_at", "-updated_at"]) -> "BoardQuery":  # type: ignore[override]
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "BoardQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "BoardQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "BoardQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["created_at", "description", "id", "name", "project", "project_id", "updated_at"]) -> "BoardQuery":  # type: ignore[override]
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "BoardQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "BoardQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "BoardQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "BoardQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "BoardQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["created_at", "description", "id", "name", "project", "project_id", "updated_at"]) -> "BoardQuery":  # type: ignore[override]
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "BoardQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["created_at", "description", "id", "name", "project", "project_id", "updated_at"]) -> "BoardQuery":  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "description", "id", "name", "project", "project_id", "updated_at"], flat: bool = False) -> "BoardQuery":  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Board]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Board | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Board | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(  # type: ignore[override]
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class BoardManager(QueryManager[Board]):
    """Type-safe Manager for Board model."""

    # Query building methods (sync, return Query)

    def query(self) -> BoardQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        project: Project | None = None,
        project__in: list[Project] | None = None,
        project__isnull: bool | None = None,
        project_id: int | None = None,
        project_id__gt: int | None = None,
        project_id__gte: int | None = None,
        project_id__lt: int | None = None,
        project_id__lte: int | None = None,
        project_id__between: tuple[int, int] | None = None,
        project_id__range: int | None = None,
        project_id__in: list[int] | None = None,
        project_id__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> BoardQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        project: Project | None = None,
        project__in: list[Project] | None = None,
        project__isnull: bool | None = None,
        project_id: int | None = None,
        project_id__gt: int | None = None,
        project_id__gte: int | None = None,
        project_id__lt: int | None = None,
        project_id__lte: int | None = None,
        project_id__between: tuple[int, int] | None = None,
        project_id__range: int | None = None,
        project_id__in: list[int] | None = None,
        project_id__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> BoardQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["created_at", "description", "id", "name", "project", "project_id", "updated_at"]) -> BoardQuery:  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "description", "id", "name", "project", "project_id", "updated_at"], flat: bool = False) -> BoardQuery:  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> BoardQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> BoardQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> BoardQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> BoardQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> BoardQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Board:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Board | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[Board, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def update_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[Board, bool]:
        """Get object, create if missing, or update it when defaults are provided."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[Board]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Board | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Board | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(  # type: ignore[override]
        self,
        *,
        instance: Board | None = None,
        client: Any | None = None,
        using: str | None = None,
        created_at: datetime | None = None,
        description: str | None = None,
        id: int | None = None,
        name: str | None = None,
        project: Project | None = None,
        project_id: int | None = None,
        updated_at: datetime | None = None,
    ) -> Board:
        """Create new object."""
        ...

    async def bulk_create(  # type: ignore[override]
        self,
        objects: list[Board],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Board]:
        """Bulk create objects."""
        ...

    async def bulk_update(  # type: ignore[override]
        self,
        objects: list[Board],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...


class Column(Model):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    board: Board | None
    name: str
    position: int
    created_at: datetime | None
    updated_at: datetime | None
    board_id: int | None
    objects: ClassVar["ColumnManager"]


class ColumnQuery(Query[Column]):
    """Type-safe Query for Column model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        board: Board | None = None,
        board__in: list[Board] | None = None,
        board__isnull: bool | None = None,
        board_id: int | None = None,
        board_id__gt: int | None = None,
        board_id__gte: int | None = None,
        board_id__lt: int | None = None,
        board_id__lte: int | None = None,
        board_id__between: tuple[int, int] | None = None,
        board_id__range: int | None = None,
        board_id__in: list[int] | None = None,
        board_id__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        position: int | None = None,
        position__gt: int | None = None,
        position__gte: int | None = None,
        position__lt: int | None = None,
        position__lte: int | None = None,
        position__between: tuple[int, int] | None = None,
        position__range: int | None = None,
        position__in: list[int] | None = None,
        position__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "ColumnQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        board: Board | None = None,
        board__in: list[Board] | None = None,
        board__isnull: bool | None = None,
        board_id: int | None = None,
        board_id__gt: int | None = None,
        board_id__gte: int | None = None,
        board_id__lt: int | None = None,
        board_id__lte: int | None = None,
        board_id__between: tuple[int, int] | None = None,
        board_id__range: int | None = None,
        board_id__in: list[int] | None = None,
        board_id__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        position: int | None = None,
        position__gt: int | None = None,
        position__gte: int | None = None,
        position__lt: int | None = None,
        position__lte: int | None = None,
        position__between: tuple[int, int] | None = None,
        position__range: int | None = None,
        position__in: list[int] | None = None,
        position__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "ColumnQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["board", "-board", "board_id", "-board_id", "created_at", "-created_at", "id", "-id", "name", "-name", "position", "-position", "updated_at", "-updated_at"]) -> "ColumnQuery":  # type: ignore[override]
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "ColumnQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "ColumnQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "ColumnQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["board", "board_id", "created_at", "id", "name", "position", "updated_at"]) -> "ColumnQuery":  # type: ignore[override]
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "ColumnQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "ColumnQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "ColumnQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "ColumnQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "ColumnQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["board", "board_id", "created_at", "id", "name", "position", "updated_at"]) -> "ColumnQuery":  # type: ignore[override]
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "ColumnQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["board", "board_id", "created_at", "id", "name", "position", "updated_at"]) -> "ColumnQuery":  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["board", "board_id", "created_at", "id", "name", "position", "updated_at"], flat: bool = False) -> "ColumnQuery":  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Column]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Column | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Column | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(  # type: ignore[override]
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class ColumnManager(QueryManager[Column]):
    """Type-safe Manager for Column model."""

    # Query building methods (sync, return Query)

    def query(self) -> ColumnQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        board: Board | None = None,
        board__in: list[Board] | None = None,
        board__isnull: bool | None = None,
        board_id: int | None = None,
        board_id__gt: int | None = None,
        board_id__gte: int | None = None,
        board_id__lt: int | None = None,
        board_id__lte: int | None = None,
        board_id__between: tuple[int, int] | None = None,
        board_id__range: int | None = None,
        board_id__in: list[int] | None = None,
        board_id__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        position: int | None = None,
        position__gt: int | None = None,
        position__gte: int | None = None,
        position__lt: int | None = None,
        position__lte: int | None = None,
        position__between: tuple[int, int] | None = None,
        position__range: int | None = None,
        position__in: list[int] | None = None,
        position__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> ColumnQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        board: Board | None = None,
        board__in: list[Board] | None = None,
        board__isnull: bool | None = None,
        board_id: int | None = None,
        board_id__gt: int | None = None,
        board_id__gte: int | None = None,
        board_id__lt: int | None = None,
        board_id__lte: int | None = None,
        board_id__between: tuple[int, int] | None = None,
        board_id__range: int | None = None,
        board_id__in: list[int] | None = None,
        board_id__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        position: int | None = None,
        position__gt: int | None = None,
        position__gte: int | None = None,
        position__lt: int | None = None,
        position__lte: int | None = None,
        position__between: tuple[int, int] | None = None,
        position__range: int | None = None,
        position__in: list[int] | None = None,
        position__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> ColumnQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["board", "board_id", "created_at", "id", "name", "position", "updated_at"]) -> ColumnQuery:  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["board", "board_id", "created_at", "id", "name", "position", "updated_at"], flat: bool = False) -> ColumnQuery:  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> ColumnQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> ColumnQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> ColumnQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> ColumnQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> ColumnQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Column:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Column | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[Column, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def update_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[Column, bool]:
        """Get object, create if missing, or update it when defaults are provided."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[Column]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Column | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Column | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(  # type: ignore[override]
        self,
        *,
        instance: Column | None = None,
        client: Any | None = None,
        using: str | None = None,
        board: Board | None = None,
        board_id: int | None = None,
        created_at: datetime | None = None,
        id: int | None = None,
        name: str | None = None,
        position: int | None = None,
        updated_at: datetime | None = None,
    ) -> Column:
        """Create new object."""
        ...

    async def bulk_create(  # type: ignore[override]
        self,
        objects: list[Column],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Column]:
        """Bulk create objects."""
        ...

    async def bulk_update(  # type: ignore[override]
        self,
        objects: list[Column],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...


class Task(Model):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    column: Column | None
    title: str
    description: str | None
    position: int
    assignee: User | None
    parent: Task | None
    created_at: datetime | None
    updated_at: datetime | None
    column_id: int | None
    assignee_id: int | None
    parent_id: int | None
    objects: ClassVar["TaskManager"]


class TaskQuery(Query[Task]):
    """Type-safe Query for Task model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        assignee: User | None = None,
        assignee__in: list[User] | None = None,
        assignee__isnull: bool | None = None,
        assignee_id: int | None = None,
        assignee_id__gt: int | None = None,
        assignee_id__gte: int | None = None,
        assignee_id__lt: int | None = None,
        assignee_id__lte: int | None = None,
        assignee_id__between: tuple[int, int] | None = None,
        assignee_id__range: int | None = None,
        assignee_id__in: list[int] | None = None,
        assignee_id__isnull: bool | None = None,
        column: Column | None = None,
        column__in: list[Column] | None = None,
        column__isnull: bool | None = None,
        column_id: int | None = None,
        column_id__gt: int | None = None,
        column_id__gte: int | None = None,
        column_id__lt: int | None = None,
        column_id__lte: int | None = None,
        column_id__between: tuple[int, int] | None = None,
        column_id__range: int | None = None,
        column_id__in: list[int] | None = None,
        column_id__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        parent: Task | None = None,
        parent__in: list[Task] | None = None,
        parent__isnull: bool | None = None,
        parent_id: int | None = None,
        parent_id__gt: int | None = None,
        parent_id__gte: int | None = None,
        parent_id__lt: int | None = None,
        parent_id__lte: int | None = None,
        parent_id__between: tuple[int, int] | None = None,
        parent_id__range: int | None = None,
        parent_id__in: list[int] | None = None,
        parent_id__isnull: bool | None = None,
        position: int | None = None,
        position__gt: int | None = None,
        position__gte: int | None = None,
        position__lt: int | None = None,
        position__lte: int | None = None,
        position__between: tuple[int, int] | None = None,
        position__range: int | None = None,
        position__in: list[int] | None = None,
        position__isnull: bool | None = None,
        title: str | None = None,
        title__contains: str | None = None,
        title__icontains: str | None = None,
        title__startswith: str | None = None,
        title__istartswith: str | None = None,
        title__endswith: str | None = None,
        title__iendswith: str | None = None,
        title__iexact: str | None = None,
        title__in: list[str] | None = None,
        title__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "TaskQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        assignee: User | None = None,
        assignee__in: list[User] | None = None,
        assignee__isnull: bool | None = None,
        assignee_id: int | None = None,
        assignee_id__gt: int | None = None,
        assignee_id__gte: int | None = None,
        assignee_id__lt: int | None = None,
        assignee_id__lte: int | None = None,
        assignee_id__between: tuple[int, int] | None = None,
        assignee_id__range: int | None = None,
        assignee_id__in: list[int] | None = None,
        assignee_id__isnull: bool | None = None,
        column: Column | None = None,
        column__in: list[Column] | None = None,
        column__isnull: bool | None = None,
        column_id: int | None = None,
        column_id__gt: int | None = None,
        column_id__gte: int | None = None,
        column_id__lt: int | None = None,
        column_id__lte: int | None = None,
        column_id__between: tuple[int, int] | None = None,
        column_id__range: int | None = None,
        column_id__in: list[int] | None = None,
        column_id__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        parent: Task | None = None,
        parent__in: list[Task] | None = None,
        parent__isnull: bool | None = None,
        parent_id: int | None = None,
        parent_id__gt: int | None = None,
        parent_id__gte: int | None = None,
        parent_id__lt: int | None = None,
        parent_id__lte: int | None = None,
        parent_id__between: tuple[int, int] | None = None,
        parent_id__range: int | None = None,
        parent_id__in: list[int] | None = None,
        parent_id__isnull: bool | None = None,
        position: int | None = None,
        position__gt: int | None = None,
        position__gte: int | None = None,
        position__lt: int | None = None,
        position__lte: int | None = None,
        position__between: tuple[int, int] | None = None,
        position__range: int | None = None,
        position__in: list[int] | None = None,
        position__isnull: bool | None = None,
        title: str | None = None,
        title__contains: str | None = None,
        title__icontains: str | None = None,
        title__startswith: str | None = None,
        title__istartswith: str | None = None,
        title__endswith: str | None = None,
        title__iendswith: str | None = None,
        title__iexact: str | None = None,
        title__in: list[str] | None = None,
        title__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "TaskQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["assignee", "-assignee", "assignee_id", "-assignee_id", "column", "-column", "column_id", "-column_id", "created_at", "-created_at", "description", "-description", "id", "-id", "parent", "-parent", "parent_id", "-parent_id", "position", "-position", "title", "-title", "updated_at", "-updated_at"]) -> "TaskQuery":  # type: ignore[override]
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "TaskQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "TaskQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "TaskQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["assignee", "assignee_id", "column", "column_id", "created_at", "description", "id", "parent", "parent_id", "position", "title", "updated_at"]) -> "TaskQuery":  # type: ignore[override]
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "TaskQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "TaskQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "TaskQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "TaskQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "TaskQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["assignee", "assignee_id", "column", "column_id", "created_at", "description", "id", "parent", "parent_id", "position", "title", "updated_at"]) -> "TaskQuery":  # type: ignore[override]
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "TaskQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["assignee", "assignee_id", "column", "column_id", "created_at", "description", "id", "parent", "parent_id", "position", "title", "updated_at"]) -> "TaskQuery":  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["assignee", "assignee_id", "column", "column_id", "created_at", "description", "id", "parent", "parent_id", "position", "title", "updated_at"], flat: bool = False) -> "TaskQuery":  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Task]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Task | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Task | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(  # type: ignore[override]
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class TaskManager(QueryManager[Task]):
    """Type-safe Manager for Task model."""

    # Query building methods (sync, return Query)

    def query(self) -> TaskQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        assignee: User | None = None,
        assignee__in: list[User] | None = None,
        assignee__isnull: bool | None = None,
        assignee_id: int | None = None,
        assignee_id__gt: int | None = None,
        assignee_id__gte: int | None = None,
        assignee_id__lt: int | None = None,
        assignee_id__lte: int | None = None,
        assignee_id__between: tuple[int, int] | None = None,
        assignee_id__range: int | None = None,
        assignee_id__in: list[int] | None = None,
        assignee_id__isnull: bool | None = None,
        column: Column | None = None,
        column__in: list[Column] | None = None,
        column__isnull: bool | None = None,
        column_id: int | None = None,
        column_id__gt: int | None = None,
        column_id__gte: int | None = None,
        column_id__lt: int | None = None,
        column_id__lte: int | None = None,
        column_id__between: tuple[int, int] | None = None,
        column_id__range: int | None = None,
        column_id__in: list[int] | None = None,
        column_id__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        parent: Task | None = None,
        parent__in: list[Task] | None = None,
        parent__isnull: bool | None = None,
        parent_id: int | None = None,
        parent_id__gt: int | None = None,
        parent_id__gte: int | None = None,
        parent_id__lt: int | None = None,
        parent_id__lte: int | None = None,
        parent_id__between: tuple[int, int] | None = None,
        parent_id__range: int | None = None,
        parent_id__in: list[int] | None = None,
        parent_id__isnull: bool | None = None,
        position: int | None = None,
        position__gt: int | None = None,
        position__gte: int | None = None,
        position__lt: int | None = None,
        position__lte: int | None = None,
        position__between: tuple[int, int] | None = None,
        position__range: int | None = None,
        position__in: list[int] | None = None,
        position__isnull: bool | None = None,
        title: str | None = None,
        title__contains: str | None = None,
        title__icontains: str | None = None,
        title__startswith: str | None = None,
        title__istartswith: str | None = None,
        title__endswith: str | None = None,
        title__iendswith: str | None = None,
        title__iexact: str | None = None,
        title__in: list[str] | None = None,
        title__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> TaskQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        assignee: User | None = None,
        assignee__in: list[User] | None = None,
        assignee__isnull: bool | None = None,
        assignee_id: int | None = None,
        assignee_id__gt: int | None = None,
        assignee_id__gte: int | None = None,
        assignee_id__lt: int | None = None,
        assignee_id__lte: int | None = None,
        assignee_id__between: tuple[int, int] | None = None,
        assignee_id__range: int | None = None,
        assignee_id__in: list[int] | None = None,
        assignee_id__isnull: bool | None = None,
        column: Column | None = None,
        column__in: list[Column] | None = None,
        column__isnull: bool | None = None,
        column_id: int | None = None,
        column_id__gt: int | None = None,
        column_id__gte: int | None = None,
        column_id__lt: int | None = None,
        column_id__lte: int | None = None,
        column_id__between: tuple[int, int] | None = None,
        column_id__range: int | None = None,
        column_id__in: list[int] | None = None,
        column_id__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        parent: Task | None = None,
        parent__in: list[Task] | None = None,
        parent__isnull: bool | None = None,
        parent_id: int | None = None,
        parent_id__gt: int | None = None,
        parent_id__gte: int | None = None,
        parent_id__lt: int | None = None,
        parent_id__lte: int | None = None,
        parent_id__between: tuple[int, int] | None = None,
        parent_id__range: int | None = None,
        parent_id__in: list[int] | None = None,
        parent_id__isnull: bool | None = None,
        position: int | None = None,
        position__gt: int | None = None,
        position__gte: int | None = None,
        position__lt: int | None = None,
        position__lte: int | None = None,
        position__between: tuple[int, int] | None = None,
        position__range: int | None = None,
        position__in: list[int] | None = None,
        position__isnull: bool | None = None,
        title: str | None = None,
        title__contains: str | None = None,
        title__icontains: str | None = None,
        title__startswith: str | None = None,
        title__istartswith: str | None = None,
        title__endswith: str | None = None,
        title__iendswith: str | None = None,
        title__iexact: str | None = None,
        title__in: list[str] | None = None,
        title__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> TaskQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["assignee", "assignee_id", "column", "column_id", "created_at", "description", "id", "parent", "parent_id", "position", "title", "updated_at"]) -> TaskQuery:  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["assignee", "assignee_id", "column", "column_id", "created_at", "description", "id", "parent", "parent_id", "position", "title", "updated_at"], flat: bool = False) -> TaskQuery:  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> TaskQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> TaskQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> TaskQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> TaskQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> TaskQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Task:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Task | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[Task, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def update_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[Task, bool]:
        """Get object, create if missing, or update it when defaults are provided."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[Task]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Task | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Task | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(  # type: ignore[override]
        self,
        *,
        instance: Task | None = None,
        client: Any | None = None,
        using: str | None = None,
        assignee: User | None = None,
        assignee_id: int | None = None,
        column: Column | None = None,
        column_id: int | None = None,
        created_at: datetime | None = None,
        description: str | None = None,
        id: int | None = None,
        parent: Task | None = None,
        parent_id: int | None = None,
        position: int | None = None,
        title: str | None = None,
        updated_at: datetime | None = None,
    ) -> Task:
        """Create new object."""
        ...

    async def bulk_create(  # type: ignore[override]
        self,
        objects: list[Task],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Task]:
        """Bulk create objects."""
        ...

    async def bulk_update(  # type: ignore[override]
        self,
        objects: list[Task],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...

