"""Auto-generated migration.

Created: 2026-06-20 23:45:00
"""

depends_on = "0005_add_project_groups"


def upgrade(ctx):
    """Apply migration."""
    ctx.create_table(
        "course",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": True,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "name",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "description",
                "python_type": "str",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "created_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "updated_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "created_by_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        foreign_keys=[
            {
                "name": "fk_course_created_by_id",
                "columns": ["created_by_id"],
                "ref_table": "user",
                "ref_columns": ["id"],
                "on_delete": "SET NULL",
                "on_update": "CASCADE",
            }
        ],
        indexes=[
            {
                "name": "idx_course_name",
                "fields": ["name"],
                "unique": True,
            }
        ],
    )
    ctx.create_table(
        "lecture",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": True,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "title",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "content",
                "python_type": "str",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "position",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "state",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "draft",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "created_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "updated_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "course_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        foreign_keys=[
            {
                "name": "fk_lecture_course_id",
                "columns": ["course_id"],
                "ref_table": "course",
                "ref_columns": ["id"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
        indexes=[
            {
                "name": "idx_lecture_course_id_title",
                "fields": ["course_id", "title"],
                "unique": True,
            }
        ],
    )
    ctx.create_table(
        "course_group",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": True,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "name",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "description",
                "python_type": "str",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "created_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "updated_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "course_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        foreign_keys=[
            {
                "name": "fk_course_group_course_id",
                "columns": ["course_id"],
                "ref_table": "course",
                "ref_columns": ["id"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
        indexes=[
            {
                "name": "idx_course_group_course_id_name",
                "fields": ["course_id", "name"],
                "unique": True,
            }
        ],
    )
    ctx.create_table(
        "course_group_permission",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": True,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "permission",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "group_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        foreign_keys=[
            {
                "name": "fk_course_group_permission_group_id",
                "columns": ["group_id"],
                "ref_table": "course_group",
                "ref_columns": ["id"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
        indexes=[
            {
                "name": "idx_course_group_permission_group_id_permission",
                "fields": ["group_id", "permission"],
                "unique": True,
            }
        ],
    )
    ctx.create_table(
        "course_member",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": True,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "created_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "group_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "user_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        foreign_keys=[
            {
                "name": "fk_course_member_group_id",
                "columns": ["group_id"],
                "ref_table": "course_group",
                "ref_columns": ["id"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            },
            {
                "name": "fk_course_member_user_id",
                "columns": ["user_id"],
                "ref_table": "user",
                "ref_columns": ["id"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            },
        ],
        indexes=[
            {
                "name": "idx_course_member_group_id_user_id",
                "fields": ["group_id", "user_id"],
                "unique": True,
            }
        ],
    )


def downgrade(ctx):
    """Revert migration."""
    ctx.drop_table("course_member")
    ctx.drop_table("course_group_permission")
    ctx.drop_table("course_group")
    ctx.drop_table("lecture")
    ctx.drop_table("course")
