"""Auto-generated migration.

Created: 2026-06-21 19:00:00
"""

depends_on = "0006_add_lms"


def upgrade(ctx):
    """Apply migration."""
    ctx.create_table(
        "git_repo",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "project_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "name",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "path",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "description",
                "python_type": "str",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "public",
                "python_type": "bool",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "default_branch",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "'main'",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "tests_enabled",
                "python_type": "bool",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "test_command",
                "python_type": "str",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "created_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "updated_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        foreign_keys=[
            {
                "name": "fk_git_repo_project_id",
                "columns": ["project_id"],
                "ref_table": "project",
                "ref_columns": ["id"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
        indexes=[
            {
                "name": "idx_git_repo_name",
                "fields": ["name"],
                "unique": True,
            },
            {
                "name": "idx_git_repo_path",
                "fields": ["path"],
                "unique": True,
            },
            {
                "name": "idx_git_repo_project_id",
                "fields": ["project_id"],
                "unique": False,
            },
        ],
    )
    ctx.create_table(
        "git_permission",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "user_email",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "access",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "'read'",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "created_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "repo_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        foreign_keys=[
            {
                "name": "fk_git_permission_repo_id",
                "columns": ["repo_id"],
                "ref_table": "git_repo",
                "ref_columns": ["id"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
        indexes=[
            {
                "name": "idx_git_permission_repo_id_user_email",
                "fields": ["repo_id", "user_email"],
                "unique": True,
            }
        ],
    )
    ctx.create_table(
        "git_push_log",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "ref",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "old_rev",
                "python_type": "str",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "new_rev",
                "python_type": "str",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "pusher_email",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "status",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "'pending'",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "output",
                "python_type": "str",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "created_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "updated_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "repo_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        foreign_keys=[
            {
                "name": "fk_git_push_log_repo_id",
                "columns": ["repo_id"],
                "ref_table": "git_repo",
                "ref_columns": ["id"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
    )
    ctx.create_table(
        "git_commit_task_ref",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "task_id",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "commit_sha",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "relation",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "'refer'",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "created_at",
                "python_type": "datetime",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "repo_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        foreign_keys=[
            {
                "name": "fk_git_commit_task_ref_repo_id",
                "columns": ["repo_id"],
                "ref_table": "git_repo",
                "ref_columns": ["id"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
        indexes=[
            {
                "name": "idx_git_commit_task_ref_unique",
                "fields": ["repo_id", "task_id", "commit_sha", "relation"],
                "unique": True,
            }
        ],
    )


def downgrade(ctx):
    """Revert migration."""
    ctx.drop_table("git_commit_task_ref")
    ctx.drop_table("git_push_log")
    ctx.drop_table("git_permission")
    ctx.drop_table("git_repo")
