from freenit.models.git import GitRepo

if GitRepo.dbtype() == "sql":
    from .store_sql import (
        check_access,
        count_repos_by_name_or_path,
        create_commit_task_ref,
        create_permission,
        create_push_log,
        create_repo,
        delete_permission,
        delete_repo,
        get_commit_task_ref_map,
        get_permission,
        get_push_log,
        get_repo,
        get_repo_by_name,
        list_commit_task_refs,
        list_commit_task_refs_by_commit,
        list_commit_task_refs_by_task,
        list_permissions,
        list_push_logs,
        list_repos,
        update_push_status,
        update_repo,
    )
elif GitRepo.dbtype() == "ldap":
    from .store_ldap import (
        check_access,
        count_repos_by_name_or_path,
        create_commit_task_ref,
        create_permission,
        create_push_log,
        create_repo,
        delete_permission,
        delete_repo,
        get_commit_task_ref_map,
        get_permission,
        get_push_log,
        get_repo,
        get_repo_by_name,
        list_commit_task_refs,
        list_commit_task_refs_by_commit,
        list_commit_task_refs_by_task,
        list_permissions,
        list_push_logs,
        list_repos,
        update_push_status,
        update_repo,
    )
else:
    raise RuntimeError(f"Unsupported git backend: {GitRepo.dbtype()}")

__all__ = [
    "check_access",
    "count_repos_by_name_or_path",
    "create_commit_task_ref",
    "create_permission",
    "create_push_log",
    "create_repo",
    "delete_permission",
    "delete_repo",
    "get_commit_task_ref_map",
    "get_permission",
    "get_push_log",
    "get_repo",
    "get_repo_by_name",
    "list_commit_task_refs",
    "list_commit_task_refs_by_commit",
    "list_commit_task_refs_by_task",
    "list_permissions",
    "list_push_logs",
    "list_repos",
    "update_push_status",
    "update_repo",
]
