---
- name: install devel packages
  with_items: "{{ devel_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart uwsgi

- name: create uwsgi conf dir
  file:
    path: /usr/local/etc/uwsgi
    mode: 0755
    owner: root
    group: wheel
    state: directory

- name: create project repo dir
  file:
    path: /usr/local/repos
    mode: 0755
    owner: uwsgi
    group: uwsgi
    state: directory

- name: configure uwsgi
  template:
    src: uwsgi.ini.j2
    dest: /usr/local/etc/uwsgi/uwsgi.ini
  notify:
    - restart uwsgi

- name: configure uwsgi service
  template:
    src: uwsgi.j2
    dest: /etc/rc.conf.d/uwsgi
  notify:
    - restart uwsgi
